# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"hello_nbdev": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://logancyang.github.io/my_exploration/"

git_url = "https://github.com/logancyang/my_exploration/tree/master/"

def custom_doc_links(name): return None
